### ISSUE TITLE
HMR is raising a preload warning in console

### ISSUE THREAD

**Issue by npearson72** [ElMassimo/vite_ruby#247]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Using `vite_client_tag`, I'm seeing the following in my browser's console:

```
The resource http://localhost:3001/vite-dev/@vite/client was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

I can't share too much in the way of logs or any other details because of the nature of project, but I can share that adding `defer: true` to the helper fixes the issue:

Example:

```
  def vite_client_tag
    return unless src = vite_manifest.vite_client_src

    javascript_include_tag(src, type: 'module', extname: false, defer: true)
  end
```

I believe `defer: true` is the correct option here, though not 100% familiar with how HMR is processed in Vite.

If this is an issue anyone else is having, I'd be happy to add a PR for it. Otherwise, just use this report as point of reference.

**Comment by ElMassimo** [comment]
Hi Nathan, thanks for reporting.

Probably related to the combination of an old Rails version and:

- https://github.com/ElMassimo/vite_ruby/pull/238

It's likely that you are running in an environment where early response hints are enabled, and Rails is sending a header to let the browser preload the script.

The mismatch is probably related to the fact that the client script is a module, and you are running in an old Rails version that sends hints incorrectly for module scripts.

I've fixed Rails behavior in:

- https://github.com/rails/rails/pull/41697

Please try applying that patch, and let me know how it goes

**Comment by npearson72** [comment]
I'm using `vite_rails-3.0.12` and `rails-6.1.6.1`, so I'm seeing these patches in the code but nevertheless the problem appears.

I've disabled all script tags on the page except:

```
<script src="/vite-dev/@vite/client" type="module"></script> <!-- Enables HMR in development only -->
<script src="/vite-dev/entrypoints/application.js" crossorigin="anonymous" type="module"></script>
```

Here's my vite config (pretty straight forward):

```
import { defineConfig } from 'vite';
import RubyPlugin from 'vite-plugin-ruby';
import vue from '@vitejs/plugin-vue2';
import path from 'path';

export default defineConfig({
  plugins: [RubyPlugin(), vue()],
  resolve: {
    alias: {
      vue: 'vue/dist/vue.esm',
      '@images': path.resolve(__dirname, 'app/assets/images'),
      '@vue_root': path.resolve(__dirname, 'app/javascript/vue'),
    },
    extensions: ['.js', '.json', '.vue']
  }
});
```

Still getting the warning.

The first warning is:

```
A preload for 'http://localhost:3001/vite-dev/@vite/client' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
```

Then it's followed by:

```
The resource http://localhost:3001/vite-dev/@vite/client was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by npearson72** [comment]
Also, I am seeing your Rails patch in my `lib/action_view/helpers/asset_tag_helper.rb`

```
      def javascript_include_tag(*sources)
        options = sources.extract_options!.stringify_keys
        path_options = options.extract!("protocol", "extname", "host", "skip_pipeline").symbolize_keys
        preload_links = []
        nopush = options["nopush"].nil? ? true : options.delete("nopush")
        crossorigin = options.delete("crossorigin")
        crossorigin = "anonymous" if crossorigin == true
        integrity = options["integrity"]

        sources_tags = sources.uniq.map { |source|
          href = path_to_javascript(source, path_options)
          if preload_links_header && !options["defer"]
            preload_link = "<#{href}>; rel=preload; as=script"
            preload_link += "; crossorigin=#{crossorigin}" unless crossorigin.nil?
            preload_link += "; integrity=#{integrity}" unless integrity.nil?
...
```

Wondering where else to look.

**Comment by npearson72** [comment]
I deleted my previous comments. You're right. After taking a closer look it seems my version of Rails does not include your patch to the `javascript_include_tag` helper.

Sorry to bother you.

Thanks for the awesome library!
